In [22]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
from sklearn import datasets
from sklearn.svm import  SVC
import numpy as np
from sklearn.metrics import accuracy_score

In [23]:
data = pd.read_csv("HorrorCookies.csv")
data.info()
data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1299 entries, 0 to 1298
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Title   1299 non-null   object
 1   Author  1299 non-null   object
 2   Year    1299 non-null   int64
 3   Rating  1299 non-null   float64
 4   Raters  1299 non-null   int64
dtypes: float64(1), int64(2), object(2)
memory usage: 50.9+ KB

,Title,Author,Year,Rating,Raters
0,The Shining (Paperback),Stephen King,1977,4.26,1331732
1,It (Paperback),Stephen King,1986,4.25,979436
2,Dracula (Paperback),Bram Stoker,1897,4.01,1119957
3,Carrie (Mass Market Paperback),Stephen King,1974,3.98,630669
4,Pet Sematary (Kindle Edition),Stephen King,1983,4.04,516341
...,...,...,...,...,...
1294,"The Cuckoo Clock of Doom (Goosebumps, #28)",R.L. Stine,1995,3.64,7614
1295,Färjan (Hardcover),Mats Strandberg,2015,3.45,3671
1296,Batman: Arkham Asylum - A Serious House on Ser...,Grant Morrison,1989,4.10,67023
1297,Missing,Missing,0,0.00,0
1298,Missing,Missing,0,0.00,0

In [24]:
data = data[data["Title"].str.contains("Missing") == False]


# discard = "Missing"
# data[~data.Title.str.contains('|'.join(discard))]
data

,Title,Author,Year,Rating,Raters
0,The Shining (Paperback),Stephen King,1977,4.26,1331732
1,It (Paperback),Stephen King,1986,4.25,979436
2,Dracula (Paperback),Bram Stoker,1897,4.01,1119957
3,Carrie (Mass Market Paperback),Stephen King,1974,3.98,630669
4,Pet Sematary (Kindle Edition),Stephen King,1983,4.04,516341
...,...,...,...,...,...
1292,The Other Black Girl (Hardcover),Zakiya Dalila Harris,2021,3.40,59940
1293,"Blood Countess (Lady Slayers, #1)",Lana Popović,2020,3.47,2136
1294,"The Cuckoo Clock of Doom (Goosebumps, #28)",R.L. Stine,1995,3.64,7614
1295,Färjan (Hardcover),Mats Strandberg,2015,3.45,3671
1296,Batman: Arkham Asylum - A Serious House on Ser...,Grant Morrison,1989,4.10,67023

In [25]:
data.to_csv("HorrorCleanedCookies.csv", index = False)
data.head()

                            Title        Author  Year  Rating   Raters
0         The Shining (Paperback)  Stephen King  1977    4.26  1331732
1                  It (Paperback)  Stephen King  1986    4.25   979436
2             Dracula (Paperback)   Bram Stoker  1897    4.01  1119957
3  Carrie (Mass Market Paperback)  Stephen King  1974    3.98   630669
4   Pet Sematary (Kindle Edition)  Stephen King  1983    4.04   516341