In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
from sklearn import datasets
from sklearn.svm import  SVC
import numpy as np
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv("HorrorAfter.csv")
data.info()
data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1196 entries, 0 to 1195
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Title   1196 non-null   object
 1   Author  1196 non-null   object
 2   Year    1196 non-null   int64
 3   Rating  1196 non-null   float64
 4   Raters  1196 non-null   int64
dtypes: float64(1), int64(2), object(2)
memory usage: 46.8+ KB

                               Title        Author  Year  Rating   Raters
0            The Shining (Paperback)  Stephen King  1977    4.25  1328811
1                     It (Paperback)  Stephen King  1986    4.25   976939
2                Dracula (Paperback)   Bram Stoker  1897    4.01  1116599
3     Carrie (Mass Market Paperback)  Stephen King  1974    3.98   628622
4      Pet Sematary (Kindle Edition)  Stephen King  1983    4.04   514701
...                              ...           ...   ...     ...      ...
1191      Under the Dome (Hardcover)  Stephen King  2009    3.91   281872
1192       The Dark Half (Paperback)  Stephen King  1989    3.80   134156
1193       Skeleton Crew (Paperback)  Stephen King  1985    3.97   118214
1194                         Missing       Missing     0    0.00        0
1195                         Missing       Missing     0    0.00        0

[1196 rows x 5 columns]

In [3]:
data = data[data["Title"].str.contains("Missing") == False]


# discard = "Missing"
# data[~data.Title.str.contains('|'.join(discard))]
data

,Title,Author,Year,Rating,Raters
0,The Shining (Paperback),Stephen King,1977,4.25,1328811
1,It (Paperback),Stephen King,1986,4.25,976939
2,Dracula (Paperback),Bram Stoker,1897,4.01,1116599
3,Carrie (Mass Market Paperback),Stephen King,1974,3.98,628622
4,Pet Sematary (Kindle Edition),Stephen King,1983,4.04,514701
...,...,...,...,...,...
1189,The Tommyknockers (Mass Market Paperback),Stephen King,1987,3.58,140413
1190,Thinner (Mass Market Paperback),Richard Bachman,1984,3.75,194749
1191,Under the Dome (Hardcover),Stephen King,2009,3.91,281872
1192,The Dark Half (Paperback),Stephen King,1989,3.80,134156
1193,Skeleton Crew (Paperback),Stephen King,1985,3.97,118214

In [4]:
data.to_csv("HorrorMissingCleaned.csv", index = False)
data.head()

                            Title        Author  Year  Rating   Raters
0         The Shining (Paperback)  Stephen King  1977    4.25  1328811
1                  It (Paperback)  Stephen King  1986    4.25   976939
2             Dracula (Paperback)   Bram Stoker  1897    4.01  1116599
3  Carrie (Mass Market Paperback)  Stephen King  1974    3.98   628622
4   Pet Sematary (Kindle Edition)  Stephen King  1983    4.04   514701